package TajweedOntology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Tue Dec 31 23:36:30 PKT 2024 by amna
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/AnatomicalUnit
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANATOMICALUNIT.<p>
     * 
     */
    public static final OWLClass CLASS_ANATOMICALUNIT = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/AnatomicalUnit"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/ApproximateArticulationPoint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPROXIMATEARTICULATIONPOINT.<p>
     * 
     */
    public static final OWLClass CLASS_APPROXIMATEARTICULATIONPOINT = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/ApproximateArticulationPoint"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/AreaOfArticulation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class AREAOFARTICULATION.<p>
     * 
     */
    public static final OWLClass CLASS_AREAOFARTICULATION = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/AreaOfArticulation"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/ArticulationPoint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTICULATIONPOINT.<p>
     * 
     */
    public static final OWLClass CLASS_ARTICULATIONPOINT = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/ArticulationPoint"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/BasicCharacteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BASICCHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_BASICCHARACTERISTIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/BasicCharacteristic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/BasicHarakaat
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BASICHARAKAAT.<p>
     * 
     */
    public static final OWLClass CLASS_BASICHARAKAAT = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/BasicHarakaat"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/Chapter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHAPTER.<p>
     * 
     */
    public static final OWLClass CLASS_CHAPTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/Chapter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/Characteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_CHARACTERISTIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/Characteristic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/CharacteristicsWithOpposite
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHARACTERISTICSWITHOPPOSITE.<p>
     * 
     */
    public static final OWLClass CLASS_CHARACTERISTICSWITHOPPOSITE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/CharacteristicsWithOpposite"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/CharacteristicsWithoutOpposite
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CHARACTERISTICSWITHOUTOPPOSITE.<p>
     * 
     */
    public static final OWLClass CLASS_CHARACTERISTICSWITHOUTOPPOSITE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/CharacteristicsWithoutOpposite"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/CompleteIdghaamRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPLETEIDGHAAMRULE.<p>
     * 
     */
    public static final OWLClass CLASS_COMPLETEIDGHAAMRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/CompleteIdghaamRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/CompleteIdghaamWithGhunnahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class COMPLETEIDGHAAMWITHGHUNNAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_COMPLETEIDGHAAMWITHGHUNNAHLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/CompleteIdghaamWithGhunnahLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/ConditionalCharacteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONDITIONALCHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_CONDITIONALCHARACTERISTIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/ConditionalCharacteristic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/DammaDammatain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DAMMADAMMATAIN.<p>
     * 
     */
    public static final OWLClass CLASS_DAMMADAMMATAIN = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/DammaDammatain"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/Diacritic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DIACRITIC.<p>
     * 
     */
    public static final OWLClass CLASS_DIACRITIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/Diacritic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/FathaDamma
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FATHADAMMA.<p>
     * 
     */
    public static final OWLClass CLASS_FATHADAMMA = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/FathaDamma"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/FathaFathatain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FATHAFATHATAIN.<p>
     * 
     */
    public static final OWLClass CLASS_FATHAFATHATAIN = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/FathaFathatain"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/FathaKasra
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FATHAKASRA.<p>
     * 
     */
    public static final OWLClass CLASS_FATHAKASRA = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/FathaKasra"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/FathainDammain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class FATHAINDAMMAIN.<p>
     * 
     */
    public static final OWLClass CLASS_FATHAINDAMMAIN = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/FathainDammain"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/GhunnahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GHUNNAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_GHUNNAHLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/GhunnahLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/GhunnahRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GHUNNAHRULE.<p>
     * 
     */
    public static final OWLClass CLASS_GHUNNAHRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/GhunnahRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/GroupOfLetters
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GROUPOFLETTERS.<p>
     * 
     */
    public static final OWLClass CLASS_GROUPOFLETTERS = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/GroupOfLetters"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HamzaLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAMZALETTER.<p>
     * 
     */
    public static final OWLClass CLASS_HAMZALETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HamzaLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HamzatulwasalRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAMZATULWASALRULE.<p>
     * 
     */
    public static final OWLClass CLASS_HAMZATULWASALRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HamzatulwasalRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HaroofAshshafawiya
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAROOFASHSHAFAWIYA.<p>
     * 
     */
    public static final OWLClass CLASS_HAROOFASHSHAFAWIYA = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HaroofAshshafawiya"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HaroofeAlthalqeeyah
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAROOFEALTHALQEEYAH.<p>
     * 
     */
    public static final OWLClass CLASS_HAROOFEALTHALQEEYAH = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HaroofeAlthalqeeyah"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HaroofeLahawiyyayn
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAROOFELAHAWIYYAYN.<p>
     * 
     */
    public static final OWLClass CLASS_HAROOFELAHAWIYYAYN = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HaroofeLahawiyyayn"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HaroofeLathawiyya
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAROOFELATHAWIYYA.<p>
     * 
     */
    public static final OWLClass CLASS_HAROOFELATHAWIYYA = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HaroofeLathawiyya"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HaroofeMadeeya
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAROOFEMADEEYA.<p>
     * 
     */
    public static final OWLClass CLASS_HAROOFEMADEEYA = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HaroofeMadeeya"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HaroofeNatiyya
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAROOFENATIYYA.<p>
     * 
     */
    public static final OWLClass CLASS_HAROOFENATIYYA = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HaroofeNatiyya"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HaroofeSaafir
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAROOFESAAFIR.<p>
     * 
     */
    public static final OWLClass CLASS_HAROOFESAAFIR = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HaroofeSaafir"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/HaroofeShajariya
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class HAROOFESHAJARIYA.<p>
     * 
     */
    public static final OWLClass CLASS_HAROOFESHAJARIYA = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/HaroofeShajariya"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IdghaamMutajanisainLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDGHAAMMUTAJANISAINLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IDGHAAMMUTAJANISAINLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IdghaamMutajanisainLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IdghaamRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDGHAAMRULE.<p>
     * 
     */
    public static final OWLClass CLASS_IDGHAAMRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IdghaamRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IdghaamShafawiLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDGHAAMSHAFAWILETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IDGHAAMSHAFAWILETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IdghaamShafawiLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IdghaamWithGhunnahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDGHAAMWITHGHUNNAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IDGHAAMWITHGHUNNAHLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IdghaamWithGhunnahLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IdghaamWithoutGhunnahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDGHAAMWITHOUTGHUNNAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IDGHAAMWITHOUTGHUNNAHLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IdghaamWithoutGhunnahLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IkhfaLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IKHFALETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IKHFALETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IkhfaLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IkhfaShafawiLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IKHFASHAFAWILETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IKHFASHAFAWILETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IkhfaShafawiLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IncompleteIdghaamRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INCOMPLETEIDGHAAMRULE.<p>
     * 
     */
    public static final OWLClass CLASS_INCOMPLETEIDGHAAMRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IncompleteIdghaamRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IncompleteIdghaamWithGhunnahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class INCOMPLETEIDGHAAMWITHGHUNNAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_INCOMPLETEIDGHAAMWITHGHUNNAHLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IncompleteIdghaamWithGhunnahLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IqlabLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IQLABLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IQLABLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IqlabLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IzharLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IZHARLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IZHARLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IzharLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/IzharShafawiLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IZHARSHAFAWILETTER.<p>
     * 
     */
    public static final OWLClass CLASS_IZHARSHAFAWILETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/IzharShafawiLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/KasraKasratain
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class KASRAKASRATAIN.<p>
     * 
     */
    public static final OWLClass CLASS_KASRAKASRATAIN = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/KasraKasratain"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/LaamRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LAAMRULE.<p>
     * 
     */
    public static final OWLClass CLASS_LAAMRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/LaamRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/Letter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LETTER.<p>
     * 
     */
    public static final OWLClass CLASS_LETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/Letter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/LetterOccurrence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LETTEROCCURRENCE.<p>
     * 
     */
    public static final OWLClass CLASS_LETTEROCCURRENCE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/LetterOccurrence"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/LexicalEntity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class LEXICALENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_LEXICALENTITY = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/LexicalEntity"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MadLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MADLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_MADLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MadLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MeddDiacritic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDDDIACRITIC.<p>
     * 
     */
    public static final OWLClass CLASS_MEDDDIACRITIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MeddDiacritic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MeddLaazim
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDDLAAZIM.<p>
     * 
     */
    public static final OWLClass CLASS_MEDDLAAZIM = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MeddLaazim"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MeddLaazimKalmi
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDDLAAZIMKALMI.<p>
     * 
     */
    public static final OWLClass CLASS_MEDDLAAZIMKALMI = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MeddLaazimKalmi"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MeddLeen
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDDLEEN.<p>
     * 
     */
    public static final OWLClass CLASS_MEDDLEEN = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MeddLeen"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MeddOnStoppingRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDDONSTOPPINGRULE.<p>
     * 
     */
    public static final OWLClass CLASS_MEDDONSTOPPINGRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MeddOnStoppingRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MeddRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDDRULE.<p>
     * 
     */
    public static final OWLClass CLASS_MEDDRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MeddRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MeddSilaRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEDDSILARULE.<p>
     * 
     */
    public static final OWLClass CLASS_MEDDSILARULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MeddSilaRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MeemSakinahRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MEEMSAKINAHRULE.<p>
     * 
     */
    public static final OWLClass CLASS_MEEMSAKINAHRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MeemSakinahRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/MiddleCharacteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MIDDLECHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_MIDDLECHARACTERISTIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/MiddleCharacteristic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NabrRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NABRRULE.<p>
     * 
     */
    public static final OWLClass CLASS_NABRRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NabrRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NaturalLeenRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NATURALLEENRULE.<p>
     * 
     */
    public static final OWLClass CLASS_NATURALLEENRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NaturalLeenRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NaturalMeddDerived
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NATURALMEDDDERIVED.<p>
     * 
     */
    public static final OWLClass CLASS_NATURALMEDDDERIVED = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NaturalMeddDerived"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NaturalMeddPrimary
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NATURALMEDDPRIMARY.<p>
     * 
     */
    public static final OWLClass CLASS_NATURALMEDDPRIMARY = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NaturalMeddPrimary"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NaturalMeddRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NATURALMEDDRULE.<p>
     * 
     */
    public static final OWLClass CLASS_NATURALMEDDRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NaturalMeddRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NonBasicDiacritic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONBASICDIACRITIC.<p>
     * 
     */
    public static final OWLClass CLASS_NONBASICDIACRITIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NonBasicDiacritic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NonGhunnahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONGHUNNAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_NONGHUNNAHLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NonGhunnahLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NonHaaYaaLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONHAAYAALETTER.<p>
     * 
     */
    public static final OWLClass CLASS_NONHAAYAALETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NonHaaYaaLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NonPronouncedDiacritic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NONPRONOUNCEDDIACRITIC.<p>
     * 
     */
    public static final OWLClass CLASS_NONPRONOUNCEDDIACRITIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NonPronouncedDiacritic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NoonSakinahAndTanweenRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOONSAKINAHANDTANWEENRULE.<p>
     * 
     */
    public static final OWLClass CLASS_NOONSAKINAHANDTANWEENRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NoonSakinahAndTanweenRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/NotKasra
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class NOTKASRA.<p>
     * 
     */
    public static final OWLClass CLASS_NOTKASRA = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/NotKasra"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/PauseMarker
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PAUSEMARKER.<p>
     * 
     */
    public static final OWLClass CLASS_PAUSEMARKER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/PauseMarker"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/PermanentTafkheemLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERMANENTTAFKHEEMLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_PERMANENTTAFKHEEMLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/PermanentTafkheemLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/PermanentTarqeeqLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PERMANENTTARQEEQLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_PERMANENTTARQEEQLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/PermanentTarqeeqLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/QalqalahLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QALQALAHLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_QALQALAHLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/QalqalahLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/QalqalahRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QALQALAHRULE.<p>
     * 
     */
    public static final OWLClass CLASS_QALQALAHRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/QalqalahRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/QamariLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class QAMARILETTER.<p>
     * 
     */
    public static final OWLClass CLASS_QAMARILETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/QamariLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/Rule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RULE.<p>
     * 
     */
    public static final OWLClass CLASS_RULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/Rule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/RuleOccurrence
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RULEOCCURRENCE.<p>
     * 
     */
    public static final OWLClass CLASS_RULEOCCURRENCE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/RuleOccurrence"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/RuleState
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RULESTATE.<p>
     * 
     */
    public static final OWLClass CLASS_RULESTATE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/RuleState"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/SecondaryMedd
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SECONDARYMEDD.<p>
     * 
     */
    public static final OWLClass CLASS_SECONDARYMEDD = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/SecondaryMedd"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/ShamsiLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SHAMSILETTER.<p>
     * 
     */
    public static final OWLClass CLASS_SHAMSILETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/ShamsiLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/SilentLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SILENTLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_SILENTLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/SilentLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/SpecificArticulationPoint
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPECIFICARTICULATIONPOINT.<p>
     * 
     */
    public static final OWLClass CLASS_SPECIFICARTICULATIONPOINT = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/SpecificArticulationPoint"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/StoppingRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STOPPINGRULE.<p>
     * 
     */
    public static final OWLClass CLASS_STOPPINGRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/StoppingRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/StrongCharacteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STRONGCHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_STRONGCHARACTERISTIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/StrongCharacteristic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/SukoonOnStopDiacritic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SUKOONONSTOPDIACRITIC.<p>
     * 
     */
    public static final OWLClass CLASS_SUKOONONSTOPDIACRITIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/SukoonOnStopDiacritic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TafkheemLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TAFKHEEMLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_TAFKHEEMLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TafkheemLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TafkheemRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TAFKHEEMRULE.<p>
     * 
     */
    public static final OWLClass CLASS_TAFKHEEMRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TafkheemRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TakhfeemPermanentRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TAKHFEEMPERMANENTRULE.<p>
     * 
     */
    public static final OWLClass CLASS_TAKHFEEMPERMANENTRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TakhfeemPermanentRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TakhfeemTemporaryRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TAKHFEEMTEMPORARYRULE.<p>
     * 
     */
    public static final OWLClass CLASS_TAKHFEEMTEMPORARYRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TakhfeemTemporaryRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/Tanween
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TANWEEN.<p>
     * 
     */
    public static final OWLClass CLASS_TANWEEN = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/Tanween"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TarqeeqLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARQEEQLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_TARQEEQLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TarqeeqLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TarqeeqRule
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TARQEEQRULE.<p>
     * 
     */
    public static final OWLClass CLASS_TARQEEQRULE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TarqeeqRule"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TemporaryTafkheemLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORARYTAFKHEEMLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORARYTAFKHEEMLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TemporaryTafkheemLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TemporaryTarqeeqLetter
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEMPORARYTARQEEQLETTER.<p>
     * 
     */
    public static final OWLClass CLASS_TEMPORARYTARQEEQLETTER = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TemporaryTarqeeqLetter"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/TypesOfCharacteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TYPESOFCHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_TYPESOFCHARACTERISTIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/TypesOfCharacteristic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/Verse
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class VERSE.<p>
     * 
     */
    public static final OWLClass CLASS_VERSE = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/Verse"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/WeakCharacteristic
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WEAKCHARACTERISTIC.<p>
     * 
     */
    public static final OWLClass CLASS_WEAKCHARACTERISTIC = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/WeakCharacteristic"));

    /* ***************************************************
     * Class http://www.semantictajweed.com/ontology/Word
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WORD.<p>
     * 
     */
    public static final OWLClass CLASS_WORD = factory.getOWLClass(IRI.create("http://www.semantictajweed.com/ontology/Word"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/belongsToGroup
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property BELONGSTOGROUP.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_BELONGSTOGROUP = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/belongsToGroup"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/composesWord
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property COMPOSESWORD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_COMPOSESWORD = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/composesWord"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/containLetter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINLETTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINLETTER = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/containLetter"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/containsLO
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property CONTAINSLO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_CONTAINSLO = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/containsLO"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/followedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property FOLLOWEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_FOLLOWEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/followedBy"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasArticulationPoint
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASARTICULATIONPOINT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASARTICULATIONPOINT = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasArticulationPoint"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasCharacteristic
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCHARACTERISTIC.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCHARACTERISTIC = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasCharacteristic"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasCharacteristicType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCHARACTERISTICTYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCHARACTERISTICTYPE = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasCharacteristicType"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasLetter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLETTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLETTER = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasLetter"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasPart
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPART.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPART = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasPart"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasRuleInstance
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRULEINSTANCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRULEINSTANCE = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasRuleInstance"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasRuleOccurrence
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRULEOCCURRENCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRULEOCCURRENCE = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasRuleOccurrence"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasRuleState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRULESTATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRULESTATE = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasRuleState"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasRuleType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRULETYPE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRULETYPE = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasRuleType"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasVerse
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASVERSE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASVERSE = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasVerse"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/hasWord
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASWORD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASWORD = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/hasWord"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/involvesAnatomicalUnit
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVESANATOMICALUNIT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVESANATOMICALUNIT = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/involvesAnatomicalUnit"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/involvesArticulationArea
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVESARTICULATIONAREA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVESARTICULATIONAREA = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/involvesArticulationArea"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/involvesDiacritic
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVESDIACRITIC.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVESDIACRITIC = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/involvesDiacritic"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/involvesLetter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVESLETTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVESLETTER = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/involvesLetter"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/involvesPauseMarker
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property INVOLVESPAUSEMARKER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_INVOLVESPAUSEMARKER = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/involvesPauseMarker"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isArticulationPointof
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISARTICULATIONPOINTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISARTICULATIONPOINTOF = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isArticulationPointof"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isCharacteristicOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCHARACTERISTICOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCHARACTERISTICOF = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isCharacteristicOf"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isCloseTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCLOSETO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCLOSETO = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isCloseTo"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isOppositeOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISOPPOSITEOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISOPPOSITEOF = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isOppositeOf"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isPartOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOF = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isPartOf"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isPartOfChapter
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFCHAPTER.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFCHAPTER = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isPartOfChapter"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isPartOfVerse
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFVERSE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFVERSE = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isPartOfVerse"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isPartOfWord
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPARTOFWORD.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPARTOFWORD = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isPartOfWord"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/isSimilarTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISSIMILARTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISSIMILARTO = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/isSimilarTo"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/occursAt
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OCCURSAT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OCCURSAT = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/occursAt"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/partiallyInvolves
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PARTIALLYINVOLVES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PARTIALLYINVOLVES = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/partiallyInvolves"));

    /* ***************************************************
     * Object Property http://www.semantictajweed.com/ontology/precededBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PRECEDEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PRECEDEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semantictajweed.com/ontology/precededBy"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/chapterIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property CHAPTERINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_CHAPTERINDEX = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/chapterIndex"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/hasAppliedTajweedDefinition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASAPPLIEDTAJWEEDDEFINITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASAPPLIEDTAJWEEDDEFINITION = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/hasAppliedTajweedDefinition"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/hasDiacriticPosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDIACRITICPOSITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDIACRITICPOSITION = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/hasDiacriticPosition"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/hasExplaination
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASEXPLAINATION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASEXPLAINATION = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/hasExplaination"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/hasLetterPosition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLETTERPOSITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLETTERPOSITION = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/hasLetterPosition"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/hasLinguisticDefinition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLINGUISTICDEFINITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLINGUISTICDEFINITION = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/hasLinguisticDefinition"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/hasSheikhAlJazareeReference
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSHEIKHALJAZAREEREFERENCE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSHEIKHALJAZAREEREFERENCE = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/hasSheikhAlJazareeReference"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/revelationOrder
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property REVELATIONORDER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_REVELATIONORDER = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/revelationOrder"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/revelationPlace
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property REVELATIONPLACE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_REVELATIONPLACE = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/revelationPlace"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/verseAbsoluteIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSEABSOLUTEINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSEABSOLUTEINDEX = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/verseAbsoluteIndex"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/verseCount
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSECOUNT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSECOUNT = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/verseCount"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/verseIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSEINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSEINDEX = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/verseIndex"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/verseText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSETEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSETEXT = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/verseText"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/wordIndex
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORDINDEX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORDINDEX = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/wordIndex"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/wordRoot
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORDROOT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORDROOT = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/wordRoot"));

    /* ***************************************************
     * Data Property http://www.semantictajweed.com/ontology/wordText
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property WORDTEXT.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_WORDTEXT = factory.getOWLDataProperty(IRI.create("http://www.semantictajweed.com/ontology/wordText"));

    /* ***************************************************
     * Data Property http://www.w3.org/2000/01/rdf-schema#label
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property rdfs_label.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_rdfs_label = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2000/01/rdf-schema#label"));

    /* ***************************************************
     * Data Property http://www.w3.org/2000/01/rdf-schema#seeAlso
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property rdfs_seeAlso.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_rdfs_seeAlso = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2000/01/rdf-schema#seeAlso"));

    /* ***************************************************
     * Data Property http://www.w3.org/2002/07/owl#sameAs
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property owl_sameAs.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_owl_sameAs = factory.getOWLDataProperty(IRI.create("http://www.w3.org/2002/07/owl#sameAs"));


}
